name: 'TroyRubert '
favicon: null
layout_spectrum: 0.1455424
typography_spectrum: 0.5655209
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: "Troy Rubert's Thoughts"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-58055580-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#CFCFCE'
    - '#8891A3'
    - '#42424B'
    - '#171727'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.7824919
purpose: []
