layout_spectrum: 0.1455424
color:
  saturation: 1
  brandStrength: 1
  lightness: 1
  brandColors:
    - '#FFFFFF'
    - '#CFCFCE'
    - '#8891A3'
    - '#42424B'
    - '#171727'
  rhythmicContrast: 0.7824919
typography_spectrum: 0.5655209
name: 'TroyRubert '
