name: 'TroyRubert '
favicon: null
layout_spectrum: 0.1455424
typography_spectrum: 0.59174
title: "Troy Rubert's Thoughts"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#cdcfce'
    - '#6a747d'
    - '#999baa'
    - '#181624'
  brandStrength: 1
  lightness: 0.3125
  saturation: 0
  rhythmicContrast: 1
purpose: []
